auth:
  type: "basic"
  client_id: ""
  callback_uri: ""
entry_points:
  - entry_point_key: ""
    artifact_id: ""
  - entry_point_key: ""
    artifact_id: ""
installation_endpoint:
  url: ""
permissions:
  - ""
  - ""
  - ""
  - ""
  - ""