version: "1.0.0"
auth:
  type: "basic"
  client_id: ""
  callback_uri: ""
entry_points:
  - entry_point_key: "PLUGIN_CONFIGURATION"
    artifact_id: "configs"
    route: "/"

admin_launchers:
  id: "admin-launcher-01"
  name: "Menu do Plugin 01"
  route: "/"
  childs:
    - id: "admin-launcher-child-01"
      name: "Submenu do Plugin 01"
      route: "/1"

    - id: "admin-launcher-child-02"
      name: "Submenu do Plugin 02"
      route: "/2"