import Layout from "@/components/Layout";
import type { Metadata } from "next";

import "@zydon/common";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html>
      <body>
        <main>
          <Layout>{children}</Layout>
        </main>
      </body>
    </html>
  );
}
